# Generated by Django 2.2.6 on 2019-10-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_auto_20191017_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name', 'summary']},
        ),
        migrations.AddField(
            model_name='genre',
            name='summary',
            field=models.TextField(default=122, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
