# Generated by Django 2.2.6 on 2019-10-25 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_auto_20191022_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
    ]
