# Generated by Django 2.2.6 on 2019-10-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_auto_20191026_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
