# Generated by Django 2.2.6 on 2019-10-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0009_auto_20191027_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
