# Generated by Django 2.2.6 on 2019-10-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0010_auto_20191027_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(default='', max_length=100),
        ),
    ]
