# Generated by Django 2.2.6 on 2019-10-27 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0013_auto_20191027_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default='No hay genero asociado', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='peliculas.Genre'),
        ),
    ]
